export type Stat =
  | 'stars'
  | 'planets'
  | 'moons'
  | 'orbits'
  | 'biosphere'
  | 'relations'
  | 'matrix'
  | 'hydrosphere'
  | 'atmosphere'
  | 'habitability'
  | 'rotation'
  | 'axial tilt'
  | 'eccentricity'
  | 'size'
  | 'population'
  | 'codes'
  | 'industry'
  | 'law'
  | 'starport'
  | 'government'
