export type Stat =
  | 'stars'
  | 'planets'
  | 'moons'
  | 'orbits'
  | 'resources'
  | 'biosphere'
  | 'relations'
  | 'hydrosphere'
  | 'atmosphere'
  | 'habitability'
  | 'size'
  | 'population'
  | 'industry'
  | 'government'
